routes:
  /:
    template: home
  /Blog/:
    template: index
  /markets/:
    template: custom-markets
  /signals/:
    template: custom-signals

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
